#the default target
eall: use_linked_list

#the def target depends on these 2 object files
#it will compile them both into the executable
use_linked_list: use_linked_list.o linked_list.o 
		gcc -Wall -o use_linked_list use_linked_list.o linked_list.o

#the main object file depends on the main.c and header file
#we compile use_linked_list.c in order to create the object file
use_linked_list.o: use_linked_list.c linked_list.h
		gcc -Wall -c use_linked_list.c

#this object file depends on linked_list.c and the header file
#we compile linked_list.c in order to create the object file
linked_list.o: linked_list.c linked_list.h
		gcc -Wall -c linked_list.c

#this target only compiles the object files
#it doesn't link them to the executable use_linked_list
compileonly: linked_list.o use_linked_list.o

#deleting all the object files
deleteobjects:
		rm -f *.o

#deleting the executable file
deleteexec:
		rm -f use_linked_list

#deleting both oject files and the executable:
deleteall: deleteexec deleteobjects
